language: node_js
node_js:
- '0.11'
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: aOUbfDEIrG+P7jpD4keCyoTr0qDPlr1HrNh7Ge2ca1PEgkgkM1xRRnsmgY7WDjGMkXROAHksShtaTkZPjusey1eIY7hYMwsxP7mgyslz4xK/wrhrOtOh2jHF+g+JpK+mFbjHFaCAMnV1lKXSLz9jGfxbI1YsWk2tdLrLje4AiblfGXjz/WamPcsbt0BMz7++y+/1+elDaD7I84GADCmzDqKW02Od3BKn5DZoLGkClD3/puiTLava8ox93KFnhuxUMdG9Wl4vJzA5JzZZjI+LcExYiQszCqbXdIFz0k9HAwFRCo43z4LUgAdxQLy2/a4FFYtsL2PKERU4ku95UPe0rRQ9Tg3Oj0+5zBcxXOB2fSRRwsJxSnEkeW99gZdoyMauOaNq8M31uu9eBt91KMlEU4BgviQic5iZq8KN8YV744cWyTBrnh+5bZywPr68sNCf5wk9rsXAHKO8EbYlfJzkKfFp5D2JSKrkqtIKqV97J2yYKHqiWkfOJ1gBly7XHuvNvzSwVqbiQ7q6k4J1AFmB+kz6/Hm649zWO4Q8/reZmuFysCuzmHa3bbrS779BfR4VnHuieHPjddAB6liYcNR3fAuXZEnaIB2Jt1BMm/7qsak6jjw+EAYb7x+xPooImG6xt9tFOcDu9pQvfGouOqdIf3enJYAmRoURFTgPnDlZSSQ=
  app: zip-api
  on:
    repo: PJankowski/zip-api
env:
  global:
    - NODE_ENV=production
  matrix:
    secure: fBpa5wm/PmtKanu/VOffWA4fX5GctiufisaeXP3xLhYuFj8Le1H22emL7plccRnXq72mW+tYkBoEki9ZSos8ewdSV6mswjOIJuK64SzE+24Z8Q6yRQrJ5jjwV3HyMWxVheKFaPc7gNJAiRQk/u+bDJsfxWsGB3UeCJZ+4FC/zq+C6HKhuho9rp4J1A1c4436987NY2jUQ4dNWJ5SD5E/0wDyefCJwGBjogo82ogC83IhPWDKgdCtkyV36x6utHzYdzmG8ljFDLkS4RhB0EIljxmt59v5dTUO+nUq5poPPxNffbgCQP5gvc6FmP26mo58xt4wMWcNErSHr6fKYyn13mR1jcNrjhfnYacnUTen6ZgPF/vn29gxMzLXlDqETK6cR0IljdkqzpxKVfk22yTQ4Zgw/yrRdOF2FzpCoeD9YjUhMwBopb0VWtFbcbEemVotf/HeXG/n4SWLqs3q8em/ieW+SAvaLDEYt9iqyNADwasAyQl3dOTnfxP26qFgINutwsrYbhkNgJP5xSNnAok/lxjmFTV0zDZ6OdgpYIO+r5xMmaygoGjxhsbnYzZplp1/XwUDZp6AS+yQbxdWbeaGy0sLltDT5Sy09IECMw41Vw4PyH7j/TPK+bWizwcnAqw/JuyRhpe8RCJ7VfYLXCWjnddVgG3U821l/CwKWOVE6oc=
